version: "3.9"

services:
  mysql-container:
    image: mysql:8.3.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    hostname: mysql-host-products-ms
    volumes:
      # - ./SqlScript:/docker-entrypoint-initdb.d
       - ./SqlScript:/docker-entrypoint-initdb.d
    networks:
      - product-msnet

  product-container:
    image: easwar1983/ecommerce-products-ms:v1.0
    container_name: product-container
    environment:
      MYSQL_HOST: mysql-host-products-ms
      MYSQL_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - product-msnet

networks:
  product-msnet:
    driver: bridge